---
- hosts: mesos-master
  remote_user: vagrant
  sudo: yes
  pre_tasks:
     - shell: echo 'I":" Beginning to configure web server..'
  roles:
     - mesos-master
  post_tasks:
     - shell: echo 'I":" Done configuring nginx web server...'


