---
- hosts: mesos-slave
  remote_user: vagrant
  sudo: yes
  pre_tasks:
     - shell: echo 'I":" Beginning to configure slave server..'
  roles:
     - mesos-slave
  post_tasks:
     - shell: echo 'I":" Done configuring nginx slave server...'


